name: lint_python
on: push
concurrency:
  cancel-in-progress: true
  group: group-${{ github.ref_name }}

jobs:
  lint_python:
    runs-on: ubuntu-latest
    services:
      pypi_wayback:
        image: ghcr.io/waleko/pypi-wayback
        ports:
        - 8629:8080
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', 3.x]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - run: pip install -U pip
    - run: pip install -U bandit mypy pyupgrade safety tox setuptools
    - run: bandit --recursive --skip B105,B110,B311,B605,B607 --exclude ./.tox .
      if: ${{ matrix.python >= '3.8' }}
    - run: tox -e lint
    - run: tox -e py
    - run: shopt -s globstar && pyupgrade --py3-only **/*.py   # --py36-plus
    - run: safety check -i 42559   # pip <= 20.1.1, we upgrade it just above
    - run: tox -e build
    - run: tox -e doc

env:
  PIP_INDEX_URL: http://localhost:8629/2023-11-05
  UV_INDEX_URL: http://localhost:8629/2023-11-05
